### ISSUE TITLE
uniref100.taxlist

### ISSUE THREAD

**Issue by gedankenstuecke** [GDKO/CGP-scripts#1]
Maybe it's a stupid question, but is there any place I can download this one or do I have to create it from the FASTA/XML provided from the EBI FTP manually? :smiley:

**Comment by GDKO** [comment]
Hi Bastian,

I will upload it to an FTP server and send you the link. I will also explain here how to generate it.

Cheers,
Georgios

**Comment by gedankenstuecke** [comment]
:+1: Thanks so much! :smiley:

**Comment by GDKO** [comment]
Created a new repo with the uniref100.taxlist file.

https://github.com/GDKO/uniref_taxlist
