### ISSUE TITLE
Defunct

### ISSUE THREAD

**Issue by evolgenomology** [GDKO/CGP-scripts#4]
Dear author,

this script does not work (anymore).

Cheers

P

**Comment by evolgenomology** [comment]
Here is something, which can eventually replace this script, but needs some work:

```
import sys
from subprocess import Popen, PIPE
import locale

encoding = locale.getdefaultlocale()[1]

# Author: Georgios Koutsovoulos

#test for diamond in PATH

#my $tool_name = "diamond";
#my $tool_path = `which $tool_name`;
#die "No $tool_name command available\n" unless ( $tool_path );

#taxmapping_file=sys.ARGV[1];
#diamond_file=sys.ARGV[2];

#die "Usage: daa_to_tagc.pl uniref100.taxlist [assembly_se_uniref.daa]\n" unless ( $uniref_file && $diamond_file );

#loading the complete tax mapping into memory might be inefficient. It is just sooo large for example for nr.

pipe = Popen('/home/philipp/bioProgs/diamond/diamond view -a /work/Ananus/NANUS_NoIndex.all.clc-se.vs.nr.e-5.daa', shell=True, stdout=PIPE)

accessions_set = set()    

#with open('/work/Ananus/lane_300bp_600bp_N300_N600_corrected.clc-se.vs.nr.e-5.6out', 'r') as daafile:
#    for line in daafile:
    #   if (len(line.split("\t"))) > 1:
    #       accessions_set.add(line.split("\t")[1].strip())

for line in pipe.stdout:
    if len(line.decode(encoding).split("\t")) > 1:
        accessions_set.add(line.decode(encoding).split("\t")[1])



mappingdict = {}

with open('/ssd2/ncbi_tax/nr.accession.taxlist', 'r') as taxmapping:
    for line in taxmapping:
        if str(line.split("\t")[0].rstrip()) in accessions_set:
            (accession, taxid) = (line.split("\t")[0].rstrip()), (line.split("\t")[1].rstrip())
            mappingdict[(accession)] = taxid

pipe2 = Popen('/home/philipp/bioProgs/diamond/diamond view -a /work/Ananus/NANUS_NoIndex.all.clc-se.vs.nr.e-5.daa', shell=True, stdout=PIPE)


with open('/work/Ananus/NANUS_NoIndex.all.clc-se.vs.nr.e-5.daa.tagc', 'w') as outfile:
    for line in pipe2.stdout:
        if len(line.decode(encoding).split("\t")) > 1:
            searchstring = str(line.decode(encoding).split("\t")[1])
            outfile.write(str(line.decode(encoding).split("\t")[0].rstrip() +"\t"+ str(mappingdict.get(searchstring)) +"\t"+line.decode(encoding).split("\t")[11].rstrip())+"\n")            

```

**Comment by GDKO** [comment]
Which script?

**Comment by evolgenomology** [comment]
daa_to_tagc.pl

Sorry, did I insert the issue in the wrong place?
It has an uninitialised variable. I think this one $unirefid.
The problem might be, that the diamond output changed, then it might a 
Perl thing. The thing is, I have two .daa files from last week with an 
old version of diamond and uniref as target and they work. Now using the 
latest version of diamond and nr as target it doesn't work. My mapping 
files are fine/the same though (btw. you will have seen that they 
abolished GIs, so now one has to use accessions in the mapping, but 
there is a flat file on the ncbi ftp).
Could it be a problem that diamond now prints the matrix (e.g. 
"blosum62") in the first line of the tabular output. At least I had to 
account for this in my Python snippet:
`for line in pipe.stdout:
if len(line.decode(encoding).split("\t")) > 1:
accessions_set.add(line.decode(encoding).split("\t")[1])`

Cheers

Phil

Georgios Koutsovoulos wrote:

**Comment by GDKO** [comment]
Can you send me a new and an old file by email?

**Comment by evolgenomology** [comment]
I just see it can't be the matrix thing. It is in the old too, or, hmmm...

Georgios Koutsovoulos wrote:

**Comment by evolgenomology** [comment]
Just sent it to your gmail address.

Georgios Koutsovoulos wrote:

**Comment by evolgenomology** [comment]
The Python I posted works just fine btw. I just don't have the time to implement the test if diamond is in PATH and calling it from the command line right now. Basically for the use of nr one could take the  [ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz](url) file directly and just select columns 2 and 3 here:
`(accession, taxid) = (line.split("\t")[0].rstrip()), (line.split("\t")[1].rstrip())`

**Comment by GDKO** [comment]
Pull the latest and try again. 
I get no errors at all. I am using diamond-v0.8.14

**Comment by evolgenomology** [comment]
Works now. Hmmm, so I had an outdated version of the script then.

Georgios Koutsovoulos wrote:

**Comment by GDKO** [comment]
I have updated it to be more universal :)

**Comment by evolgenomology** [comment]
Thanks. (still could go the python way...) ;-)

Georgios Koutsovoulos wrote:

**Comment by GDKO** [comment]
Or not :P

**Comment by evolgenomology** [comment]
pffff

Georgios Koutsovoulos wrote:

**Comment by GDKO** [comment]
Changed the code to be 3x faster!

**Comment by evolgenomology** [comment]
Just don't forget my co-authorship on all your papers then!

Georgios Koutsovoulos wrote:

**Comment by GDKO** [comment]
Consider it done!

**Comment by evolgenomology** [comment]
fyi.
time ~/bioProgs/CGP-scripts/scripts/daa_to_tagc.pl 
/ssd2/ncbi_tax/nr.accession.taxlist 
Xeno_all_pe_dipSPAdesFrom77.scaffolds.500bp.vs.nr.e-5.daa
Use of uninitialized value $columns[1] in hash element at 
/home/philipp/bioProgs/CGP-scripts/scripts/daa_to_tagc.pl line 31, 
<$cmd> line 1.

Georgios Koutsovoulos wrote:

**Comment by evolgenomology** [comment]
time ~/bioProgs/CGP-scripts/scripts/daa_to_tagc.pl 
/ssd2/ncbi_tax/nr.accession.taxlist 
Xeno_all_pe_dipSPAdesFrom77.scaffolds.500bp.vs.nr.e-5.daa
Use of uninitialized value $columns[1] in hash element at 
/home/philipp/bioProgs/CGP-scripts/scripts/daa_to_tagc.pl line 31, 
<$cmd> line 1.
Use of uninitialized value in hash element at 
/home/philipp/bioProgs/CGP-scripts/scripts/daa_to_tagc.pl line 51.
Use of uninitialized value in concatenation (.) or string at 
/home/philipp/bioProgs/CGP-scripts/scripts/daa_to_tagc.pl line 51.
~/bioProgs/CGP-scripts/scripts/daa_to_tagc.pl 257.51s user 1.94s system 
100% cpu 4:19.10 total

Is blosum62 the root of all life? :D

blosum62 1
NODE_1_length_501950_cov_1773.77 83561 2754.9
NODE_2_length_232633_cov_1742.32 83561 1394.8
NODE_3_length_188321_cov_1744.51 83561 1328.2
NODE_3_length_188321_cov_1744.51 83561 60.5

Speaking of speed and Perl vs. Python....

time python3 daa_to_tagc.py
python3 daa_to_tagc.py 221.77s user 1.63s system 101% cpu 3:40.41 total

:D :D :D

Georgios Koutsovoulos wrote:
